### ISSUE TITLE
minimum texture resolution size

### ISSUE THREAD

**Issue by eGax** [njbrown/texturelab#12]
​I've seen more and more mappers & modder use Substance Designer not realizing there was a Linux build of it. I was searching for free and open-source alternatives to it that run under Linux when I found Texturelab.

I work with a lot of older games like doom, quake, quake 2, etc and the minimum resolution size of 256 is huge relatively speaking in comparison to those game textures. Texturelab's smallest size is

![Screenshot_20200614_141548](https://user-images.githubusercontent.com/9817245/84607492-9ad3be80-ae7b-11ea-9f90-426fd4bd8ee0.png)

Sure you can use 256 and scale it down, but that adds extra steps and it sometimes helps r to work in the actual texture size you need when making textures. This may fall under the lacking UI elements you mention on the website.

It would be nice to be able to pick your own sizes or at least offer a few smaller sizes than 256x256.

**Comment by njbrown** [comment]
I'll be adding UI to allow users to choose their own resolutions. For now, I can add lower resolutions to the list. Is 128, 64 and 32 good enough?

**Comment by eGax** [comment]
> I'll be adding UI to allow users to choose their own resolutions. For now, I can add lower resolutions to the list. Is 128, 64 and 32 good enough?

Yes that opens it up a quite a bit until the is the user is allowed to pick their own. Thanks!

**Comment by njbrown** [comment]
Great. I added them to master.
