### ISSUE TITLE
Import declaration conflicts with local declaration of 'UVGenerator', and how can i use 'npm start' command?

### ISSUE THREAD

**Issue by xiaoyucai01** [njbrown/texturelab#14]
Type checking in progress...

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.20.130:8080/

ERROR in D:/Projects/Electron/texturelab/node_modules/three/src/geometries/ExtrudeGeometry.d.ts
2:10 Import declaration conflicts with local declaration of 'UVGenerator'.
    1 | import { CurvePath } from './../extras/core/CurvePath';
  > 2 | import { UVGenerator } from './ExtrudeGeometry';
      |          ^
    3 | import { Vector2 } from './../math/Vector2';
    4 | import { Vector3 } from './../math/Vector3';
    5 | import { Shape } from './../extras/core/Shape';
ERROR in D:/Projects/Electron/texturelab/node_modules/three/src/materials/ShaderMaterial.d.ts
1:10 Import declaration conflicts with local declaration of 'ShaderMaterialParameters'.
  > 1 | import { ShaderMaterialParameters } from './ShaderMaterial';
      |          ^
    2 | import { IUniform } from '../renderers/shaders/UniformsLib';
    3 | import { MaterialParameters, Material } from './Material';
    4 |
Version: typescript 3.9.6
Time: 6045ms

**Comment by njbrown** [comment]
Hey, I've always seen this issue but the project still built for me. I updated to a newer version of threejs as suggested [here ](https://discourse.threejs.org/t/tsc-error-2440-when-using-three-108-uv-generator-and-shadermaterialparameters/11937 ) and the error is now gone. Thanks.

Regarding `npm start`, are you suggesting I use it as an alias for `npm run electron:serve`?

**Comment by xiaoyucai01** [comment]
Hi, thanks for the reply. Now i run npm run electron:serve, and it is compiled successfully, but failed to open it using http://localhost:8080/ with chrome, The error is "Uncaught ReferenceError: require is not defined". I am new to npm and electron etc, I expected to open a desktop application when i run the cmd.

**Comment by iKlsR** [comment]
@xiaoyucai01 It's an electron application, it's not meant to be ran in the browser out the box. When you serve it should open an application window, if you don't see one, check the console and see if anything is off. Try deleting your `node_modules` folder and doing a clean build. Also make sure you are actually doing `electron:serve` and not just `serve`.

Also I would prefer yarn as the package manager as you get a bit more speed.

**Comment by njbrown** [comment]
@xiaoyucai01 what are your npm and node versions?

**Comment by xiaoyucai01** [comment]
@iKlsR @njbrown npm6.14.5 and node12.18.1, maybe the version is too new. [
![image](https://user-images.githubusercontent.com/37772704/86707783-e167a380-c04a-11ea-85be-55e25a57e577.png)
](url), [
![image](https://user-images.githubusercontent.com/37772704/86708165-3efbf000-c04b-11ea-95de-aed87cca3cdf.png)
](url), Above are the results, the second picture is the result that i run the "npm run electron:serve" secondly or later. There is some warnings the first time i run the cmd. Aslo, i installed yarn, and it worked, run successfully,  [
![image](https://user-images.githubusercontent.com/37772704/86713987-3ad2d100-c051-11ea-9712-8a7b345b7a9f.png)
](url)

**Comment by iKlsR** [comment]
@njbrown As a rule of thumb, stick to one package manager. They are essentially the same but there are some small inconsistencies here and there and having two lock files will cause issues when you use them interchangeably. 

I would update the readme to only build and run with yarn and drop the package-lock json.

**Comment by njbrown** [comment]
@iKlsR you have a point. If i'm going to keep them both i'm going to have to keep both .lock files up to date.
