### ISSUE TITLE
TextureLab crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by leonard7e** [njbrown/texturelab#16]
OS: Ubuntu Linux 20.04
GPU: GeForce RTX 2060 SUPER
CPU: AMD Ryzen 7 1800X

There is a strange problem. There are two computers here, both use (xfce) XUbuntu 20.04. 
TextureLab works fine on my 2-core Celeron shoebox. But on the other (Ryzen based) PC it just opens a white window. 

TextureLab's Console feedback (Ryzen system). I tried the TextureLab-AppImage and the TextureLab from compressed archive.
```
# The AppImage
leonard@LuckDragon:~$ TextureLabLinux-v0.2.0.AppImage 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

# Decompressed from archive
leonard@LuckDragon:~$ cd app/TextureLab/
leonard@LuckDragon:~/app/TextureLab$ ls
chrome_100_percent.pak  chrome-sandbox  libEGL.so     libGLESv2.so          LICENSES.chromium.html  natives_blob.bin  resources.pak      swiftshader  v8_context_snapshot.bin
chrome_200_percent.pak  icudtl.dat      libffmpeg.so  LICENSE.electron.txt  locales                 resources         snapshot_blob.bin  texturelab
leonard@LuckDragon:~/app/TextureLab$ ./texturelab 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

```

Just now I refreshed both Ubuntu systems with
sudo apt update; sudo apt upgrade
Still the same issue on the other Pc.

**Comment by iKlsR** [comment]
What happens if you try building from source?

**Comment by iKlsR** [comment]
@njbrown You might want to explicitly bump electron.

**Comment by njbrown** [comment]
Electron has already been updated. We've addressed this issue before here #11. I might have to do an interim release since this seems to be a recurring issue. 

@leonard7e are you ok with building from source and telling us if the issue has been resolved?

**Comment by leonard7e** [comment]
I am sorry, I did not look at closed issues. 

After building TextureLab, I did "npm run electron:serve".
Still screen. Used Firefox and chromium.

Screenshot
![screenshot](https://user-images.githubusercontent.com/5395270/88097707-dc513b00-cb98-11ea-8379-fd42e9af8164.jpg)

**Comment by leonard7e** [comment]
Chromium browser console shows an error message. 

![scrs_chromium](https://user-images.githubusercontent.com/5395270/88098873-bcbb1200-cb9a-11ea-819d-e9e180f5cb85.jpg)

In Firefox console, similar error message. "Uncaught ReferenceError: require is not defined"

**Comment by njbrown** [comment]
The app shouldn't be running in the inside the browser; an electron window should popup. Try using `yarn electron:serve` and let me know if it works.

@iKlsR I might just remove the `npm` instructions once and for all.

**Comment by leonard7e** [comment]
I tried with yarn.
Now TextureLab works. :-)

**Comment by njbrown** [comment]
Awesome!

@iKlsR definitely dropping `npm` instructions.

**Comment by njbrown** [comment]
@leonard7e I'd recommend building from the v0.2.0 tag since it's the latest official release. There's no guarantee of the stability of `master`.

https://github.com/njbrown/texturelab/tree/v0.2.0

**Comment by leonard7e** [comment]
Ok, I will do. Thank you for your help. :-)
