### ISSUE TITLE
Export to shadertoy (or three.js)

### ISSUE THREAD

**Issue by boulabiar** [njbrown/texturelab#2]
This application is so cool. I like how easy it is to connect components and that there are many ready to use ones.

I just have a suggestion to add a glsl exporter (to shadertoy).

Thanks :)

**Comment by njbrown** [comment]
> This application is so cool. I like how easy it is to connect components and that there are many ready to use ones.

heh thanks.

> I just have a suggestion to add a glsl exporter (to shadertoy).

This isn't possible because of the way TextureLab is structured. It's mean for generating textures, not shaders. It's a cool idea but it isn't a long-term goal of the project. 

Checkout [Material Maker](https://rodzilla.itch.io/material-maker). I think it does what you want.
