### ISSUE TITLE
Is there any  app integration?

### ISSUE THREAD

**Issue by AverageComet250** [njbrown/texturelab#20]
I know that Substance Designer has 3ds max, unity and Maya integration and I just thought I'd ask if texturelab has any of these. I've never actually used substance or texturelab, however I'm trying to pick one for making textures to use in unity and 3ds max (my 3d modelling software)

**Comment by njbrown** [comment]
There are currently no integrations for texturelab in any of these applications and there are none planned anytime soon. You can, however, export your textures from texturelab to a unity material.

Texturelab is free so there's no harm in giving it a try.
