### ISSUE TITLE
Is Mac version coming?

### ISSUE THREAD

**Issue by enzyme69** [njbrown/texturelab#4]
Hi Nic, just wondering if there is any plan to have Mac version?

**Comment by leebradley** [comment]
It definitely works on Mac. I'm running it from source and everything's functional.

**Comment by njbrown** [comment]
> It definitely works on Mac. I'm running it from source and everything's functional.

This is wonderful news to me because I've never built nor tested the app on Mac :sweat_smile:. I have very little experience with the platform.

I'll try to have mac version for download in a week.

**Comment by MadMacMad** [comment]
yep wish a Mac app too....
but well you see if the dev's are dedicated... than you have a Mac version too...
it's just hit a button... and could do same time with the other build... 
but if there is no build... better stay away... 
the dev's hate Mac user ... because they pay for software ;-)

**Comment by ItsNatoriousB** [comment]
Just tested today on Catalina 10.15.7 and things worked amazing! I've got more testing to do for feedback.

**Comment by eGax** [comment]
I think this issue could be closed now we have the Mac builds available.
