### ISSUE TITLE
some errors like this

### ISSUE THREAD

**Issue by muneebahmed26301** [njbrown/texturelab#5]
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/common/color.d.ts
85:9 An accessor cannot be declared in an ambient context.
    83 |     readonly rgba: RGBA;
    84 |     private _hsla;
  > 85 |     get hsla(): HSLA;
       |         ^
    86 |     private _hsva;
    87 |     get hsva(): HSVA;
    88 |     constructor(arg: RGBA | HSLA | HSVA);
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/common/color.d.ts
87:9 An accessor cannot be declared in an ambient context.
    85 |     get hsla(): HSLA;
    86 |     private _hsva;
  > 87 |     get hsva(): HSVA;
       |         ^
    88 |     constructor(arg: RGBA | HSLA | HSVA);
    89 |     equals(other: Color): boolean;
    90 |     /**
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/common/event.d.ts
158:9 An accessor cannot be declared in an ambient context.
    156 |      * to events from this Emitter
    157 |      */
  > 158 |     get event(): Event<T>;
        |         ^
    159 |     /**
    160 |      * To be kept private to fire an event to
    161 |      * subscribers
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/common/event.d.ts
210:9 An accessor cannot be declared in an ambient context.
    208 |     private emitter;
    209 |     readonly event: Event<T>;
  > 210 |     set input(event: Event<T>);
        |         ^
    211 |     dispose(): void;
    212 | }
    213 | export {};
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/common/lifecycle.d.ts
13:19 An accessor cannot be declared in an ambient context.
    11 |     static None: Readonly<IDisposable>;
    12 |     protected _toDispose: IDisposable[];
  > 13 |     protected get toDispose(): IDisposable[];
       |                   ^
    14 |     private _lifecycle_disposable_isDisposed;
    15 |     dispose(): void;
    16 |     protected _register<T extends IDisposable>(t: T): T;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/common/linkedList.d.ts
6:9 An accessor cannot be declared in an ambient context.
    4 |     private _last;
    5 |     private _size;
  > 6 |     get size(): number;
      |         ^
    7 |     isEmpty(): boolean;
    8 |     clear(): void;
    9 |     unshift(element: E): () => void;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menu/menu.d.ts
33:9 An accessor cannot be declared in an ambient context.
    31 |     parentData: ISubMenuData;
    32 |     private _onDidCancel;
  > 33 |     get onDidCancel(): Event<void>;
       |         ^
    34 |     constructor(container: HTMLElement, options?: IMenuOptions, closeSubMenu?: () => void);
    35 |     setAriaLabel(label: string): void;
    36 |     private isTriggerKeyEvent;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
48:9 An accessor cannot be declared in an ambient context.
    46 |     setupMenubar(): void;
    47 |     private onClick;
  > 48 |     get onVisibilityChange(): Event<boolean>;
       |         ^
    49 |     get onFocusStateChange(): Event<boolean>;
    50 |     dispose(): void;
    51 |     blur(): void;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
49:9 An accessor cannot be declared in an ambient context.
    47 |     private onClick;
    48 |     get onVisibilityChange(): Event<boolean>;
  > 49 |     get onFocusStateChange(): Event<boolean>;
       |         ^
    50 |     dispose(): void;
    51 |     blur(): void;
    52 |     setStyles(style: IMenuStyle): void;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
57:17 An accessor cannot be declared in an ambient context.
    55 |     private hideMenubar;
    56 |     private showMenubar;
  > 57 |     private get focusState();
       |                 ^
    58 |     private set focusState(value);
    59 |     private get isVisible();
    60 |     private get isFocused();
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
58:17 An accessor cannot be declared in an ambient context.
    56 |     private showMenubar;
    57 |     private get focusState();
  > 58 |     private set focusState(value);
       |                 ^
    59 |     private get isVisible();
    60 |     private get isFocused();
    61 |     private get isOpen();
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
59:17 An accessor cannot be declared in an ambient context.
    57 |     private get focusState();
    58 |     private set focusState(value);
  > 59 |     private get isVisible();
       |                 ^
    60 |     private get isFocused();
    61 |     private get isOpen();
    62 |     private setUnfocusedState;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
60:17 An accessor cannot be declared in an ambient context.
    58 |     private set focusState(value);
    59 |     private get isVisible();
  > 60 |     private get isFocused();
       |                 ^
    61 |     private get isOpen();
    62 |     private setUnfocusedState;
    63 |     private focusPrevious;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
61:17 An accessor cannot be declared in an ambient context.
    59 |     private get isVisible();
    60 |     private get isFocused();
  > 61 |     private get isOpen();
       |                 ^
    62 |     private setUnfocusedState;
    63 |     private focusPrevious;
    64 |     private focusNext;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
66:17 An accessor cannot be declared in an ambient context.
    64 |     private focusNext;
    65 |     private updateMnemonicVisibility;
  > 66 |     private get mnemonicsInUse();
       |                 ^
    67 |     private set mnemonicsInUse(value);
    68 |     private onMenuTriggered;
    69 |     private onModifierKeyToggled;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/menubar.d.ts
67:17 An accessor cannot be declared in an ambient context.
    65 |     private updateMnemonicVisibility;
    66 |     private get mnemonicsInUse();
  > 67 |     private set mnemonicsInUse(value);
       |                 ^
    68 |     private onMenuTriggered;
    69 |     private onModifierKeyToggled;
    70 |     private isCurrentMenu;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/themebar.d.ts
11:16 An accessor cannot be declared in an ambient context.
     9 |     constructor();
    10 |     protected registerTheme(theme: Theme): void;
  > 11 |     static get win(): Theme;
       |                ^
    12 |     static get mac(): Theme;
    13 | }
    14 | export interface CssStyle {
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/themebar.d.ts
12:16 An accessor cannot be declared in an ambient context.
    10 |     protected registerTheme(theme: Theme): void;
    11 |     static get win(): Theme;
  > 12 |     static get mac(): Theme;
       |                ^
    13 | }
    14 | export interface CssStyle {
    15 |     addRule(rule: string): void;
ERROR in D:/ELECTRON/texturelab/node_modules/custom-electron-titlebar/lib/titlebar.d.ts
94:9 An accessor cannot be declared in an ambient context.
    92 |      * get the options of the titlebar
    93 |      */
  > 94 |     get options(): TitlebarOptions;
       |         ^
    95 |     /**
    96 |    * Update the background color of the title bar
    97 |    * @param backgroundColor The color for the background
ERROR in D:/ELECTRON/texturelab/src/lib/designer.ts
63:5 Type 'CanvasRenderingContext2D | WebGLRenderingContext' is not assignable to type 'WebGLRenderingContext'.
  Type 'CanvasRenderingContext2D' is missing the following properties from type 'WebGLRenderingContext': drawingBufferHeight, drawingBufferWidth, activeTexture, attachShader, and 429 more.
    61 |     this.canvas.width = this.width;
    62 |     this.canvas.height = this.height;
  > 63 |     this.gl = this.canvas.getContext("webgl2");
       |     ^
    64 |
    65 |     this.nodes = new Array();
    66 |     this.conns = new Array();

**Comment by njbrown** [comment]
Thank you for reporting this. These seem to be solely type errors. Are they preventing you from running the application?
What version of typescript, node and npm(or yarn)  are you using? Also, what OS are you on?

**Comment by muneebahmed26301** [comment]
I am using Window 10 as my OS system. And i have latest version of node
,npm and typescript

**Comment by njbrown** [comment]
Someone fixed the issue by upgrading typescript:
https://github.com/storybookjs/storybook/issues/9463#issuecomment-575077542

I updated the typescript version in the package.json file. Can you try building again?
