### ISSUE TITLE
Export feature produces invalid zip

### ISSUE THREAD

**Issue by Blaster84x** [njbrown/texturelab#6]
**Environment**: Linux Mint 19.3 64-bit (Cinnamon)
**Version**: 0.1.0
**Description**: When I'm trying to open the exported texture zip and not all channels are defined, the zip file comes out invalid (unreadable) for the GNOME archive manager. It looks like you're using a binary export instead of the proper library or Electron abstraction layer.

Btw you should really set up issue templates. It makes them *way* more readable and manageable.

**Comment by njbrown** [comment]
I did notice the issue on windows but the OS's zip exporter (and 7zip even) still extracted the files, though with a warning. 

> It looks like you're using a binary export instead of the proper library or Electron abstraction layer.

What do u suggest i use?

> Btw you should really set up issue templates. It makes them way more readable and manageable.

Thanks. I will.

**Comment by Blaster84x** [comment]
You can use any of the node.js libraries (JSZip looks like the best).

**Comment by njbrown** [comment]
I did initially, but it had a bug that forced me to switch to adm-zip

**Comment by njbrown** [comment]
This issue is now fixed a8eaeb96bb614d298071a13e0b1f66f244f26370
